version: 2

project_name: git-profile

builds:
  - id: git-profile
    binary: git-profile
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.CommitHash={{.Commit}}
      - -X main.CompileDate={{.Date}}

universal_binaries:
  - id: git-profile-universal
    ids:
      - git-profile
    replace: true

archives:
  - id: git-profile
    ids:
      - git-profile
      - git-profile-universal
    files:
      - LICENSE*
      - README*
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ title .Os }}{{ end }}-
      {{- if eq .Arch "all" }}all
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: checksums.txt

source:
  enabled: true

brews:
  - name: git-profile
    homepage: https://github.com/dotzero/git-profile
    description: Git Profile allows to add and switch between multiple user profiles in git repositories
    license: MIT
    repository:
      owner: dotzero
      name: homebrew-tap
    commit_author:
      name: dotzero
      email: mail@dotzero.ru
    install: |
      system "go", "build", *std_go_args(ldflags: "-s -w -X main.Version=#{version}")

release:
  github:
    owner: dotzero
    name: git-profile
