Output demo.gif

Set FontSize 24
Set Width 1200
Set Height 500

Type "git-profile add"
Sleep 300ms
Enter
Sleep 500ms
Type "my-profile"
Sleep 300ms
Enter
Sleep 500ms
Type "John Doe"
Sleep 300ms
Enter
Sleep 500ms
Type "john@doe.com"
Sleep 300ms
Enter
Sleep 1s
Enter
Sleep 2s

Type "git-profile use"
Sleep 300ms
Enter
Sleep 500ms
Down
Sleep 300ms
Enter
Sleep 2s

Type "git-profile del"
Sleep 300ms
Enter
Sleep 500ms
Down
Sleep 300ms
Enter
Sleep 2s
